
version: '3.9'

services:
  scribnet:
    build: 
      context: .
      target: "prod"
    image: "scribnet:0.0.1"
    env_file:
      - ".env"
    environment:
      BIND_IP: "0.0.0.0"
      BIND_PORT: "3000"
    volumes:
      - "./data-folder:/app/data-folder"
    ports:
      - "8080:3000"